Issue 97: 기록 조회 예외처리 및 달리기 제한
Relay-UMC23/relay-server pull request #108
Opened 2023-02-13 03:31 UTC by dasomahn

수정사항
- 목표 종류 & 목표치를 레코드 테이블 컬럼에서 바로 갖고오도록 변경
- 하루에 한번만 달릴 수 있도록 제한
- 프로필 데일리 조회 시 기록 두개 이상인 날 예외처리
- 그룹 데일리 조회 시 기록 없는 날 예외처리
- NonUniqueResultException -> IncorrectResultSizeDataAccessException 일괄 변경
- 명세서 설명 추가(시간표 변경)

기록 조회 4가지 (프로필 데일리&먼슬리, 그룹 데일리&먼슬리) 다 제대로 작동되는지 검토 부탁드립니다!
예외처리된 내용은 아래와 같습니다
- 프로필 데일리: 해당 날짜에 기록이 없을 때, 두개 이상 있을 때
- 그룹 데일리: 해당 날짜에 기록이 없을 때
(먼슬리는 예외처리 없이, 기록이 있는 날짜들만 표시가 되고 그 달에 아무 기록도 없을 경우 빈 리스트가 반환됩니다.)

2023-02-13 14:56 UTC, Yeonji-Lim requested changes
현재 반환시 목표와 목표치가 안나오고 있어요 같이 반환되게 수정 부탁드립니다.

2023-02-13 15:37 UTC, dasomahn commented
> 현재 반환시 목표와 목표치가 안나오고 있어요 같이 반환되게 수정 부탁드립니다.

response 항목에 있는데 null로 표시되는건가요?
그런거라면 저희 그때 null로 컬럼 추가해서 그럴겁니당
새로 시작한 기록들에 대해서는 잘 뜰거에요!

2023-02-14 08:24 UTC, Yeonji-Lim commented
보니까 GetCalendar dto에 해당 값이 없어용

2023-02-14 08:32 UTC, dasomahn commented
> 보니까 GetCalendar dto에 해당 값이 없어용

월별 조회시에도 목표 종류랑 목표치를 사용하나요?
월별 조회는 캘린더 색칠할때랑 그래프 표시 정도로 쓰이는 걸로 알고있어서 세 값(일별 거리, 시간, 속도) 외에 다른 값들을 추가하지 않았습니다..!

2023-02-14 08:46 UTC, Yeonji-Lim commented
아 맞네요 어차피 달력에서 눌러서 일별 기록으로 가겠네요,,! 
나머지는 실행확인했습니당

2023-02-14 08:46 UTC, Yeonji-Lim approved these changes

2023-02-14 08:47 UTC, Yeonji-Lim commented
바로 머지하겠습니다~

2023-02-14 08:48 UTC, merged